### ISSUE TITLE
Add binder and/or docker

### ISSUE THREAD

**Issue by cranmer** [diana-hep/carl#22]
Since this requires bleeding edge of theano etc. can we 

- make a docker image and host it on docker hub (good for running locally)

- make a dockerfile for binder that extends the binder base image. Here's an example: https://github.com/cranmer/ligo-binder/blob/master/Dockerfile

**Comment by kreczko** [comment]
+1 for docker. Not only good to run locally but also in a batch system (e.g. HTCondor)

**Comment by glouppe** [comment]
While I agree we should make installation easy/easier, I am not sure what to put in such a Docker image. Carl is meant to be a library, not an application. For this reason, I am not sure to see how useful a docker image could be; in particular in the typical case one will want to use carl in a larger system, as a tool among many others.

**Comment by betatim** [comment]
IMHO the docker container would be:

* a way to document the setup steps that I can adopt for my specific setup
* preloaded with examples -> easy way to try it out and see if I actually want to use it

**Comment by kreczko** [comment]
@betatim: pretty much. For an application/analysis run one would base the app container on the carl container (`FROM diana-hep/carl`)

**Comment by cranmer** [comment]
Also, not adding the image directly to repository, just a docker file and
the image lives on docker hub

**Comment by kreczko** [comment]
@cranmer yes, otherwise the command I quoted would not work ;).

**Comment by glouppe** [comment]
I agree with Tim's documentation use case. 

However I still genuinely dont understand what is the added value for the typical use case when you will need carl as a library, among many other tools. When running my own application/analysis I would supposedly be in a situation where I want to be in control of the environment. In particular, I wouldnt want to constrain myself by inheriting from `diana-hep/carl`, e.g. because I may already be in a situation where I must inherit from something (say `ATLAS/whatever`). 

Also remember that installing carl will soon be as simple as `pip install carl`.

**Comment by cranmer** [comment]
Yeah, i agree it wouldn't be needed in standard use as a library. But
before its on pip it's useful and if people want to play with it on binder
it's needed.

Kyle

**Comment by glouppe** [comment]
I can provide a conda `environment.yml` file to run the notebooks in Binder, that should be quick. For equivalent Docker files, help is welcome though, as I never really played with this technology.

**Comment by cranmer** [comment]
:+1: if the `requirements.txt` is enough to get this to run on binder (and what you would have for pip anyways), that's probably fine.

**Comment by glouppe** [comment]
See https://github.com/diana-hep/carl-notebooks.
